# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [432]:
# Import your libraries:
import pandas as pd
from sklearn.datasets import load_diabetes

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [433]:
diabetes = load_diabetes()
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [434]:
import pandas as pd
df_diabetes =pd.DataFrame (diabetes.data, columns =diabetes.feature_names)
df_diabetes

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [435]:
df_diabetes['target'] = diabetes.target

In [436]:
df_diabetes.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [437]:
df_diabetes.shape

(442, 11)

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [438]:
df_diabetes.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,442.000000
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17,152.133484
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,77.093005
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01,25.000000
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02,87.000000
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03,140.500000
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02,211.500000
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01,346.000000

In [439]:
df_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
 10  target  442 non-null    float64
dtypes: float64(11)
memory usage: 38.1 KB

In [440]:
df_diabetes.isnull().sum()

age       0
sex       0
bmi       0
bp        0
s1        0
s2        0
s3        0
s4        0
s5        0
s6        0
target    0
dtype: int64

What are the variables in this dataset according to the description? List them in the markdown cell below

   - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

#### Enter your answer here:

age, sex, body mass index, average blood pressure, s1, s2, s3, s4, s5, s6

In [441]:
df_diabetes.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6',
       'target'],
      dtype='object')

Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [442]:
df_diabetes.shape

(442, 11)

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn.

In [443]:
X=df_diabetes.drop(columns =['target'])
y =df_diabetes['target']

In [444]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size =0.2, random_state =42)
X_train

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
17,0.070769,0.050680,0.012117,0.056301,0.034206,0.049416,-0.039719,0.034309,0.027364,-0.001078
66,-0.009147,0.050680,-0.018062,-0.033213,-0.020832,0.012152,-0.072854,0.071210,0.000272,0.019633
137,0.005383,-0.044642,0.049840,0.097615,-0.015328,-0.016345,-0.006584,-0.002592,0.017036,-0.013504
245,-0.027310,-0.044642,-0.035307,-0.029770,-0.056607,-0.058620,0.030232,-0.039493,-0.049872,-0.129483
31,-0.023677,-0.044642,-0.065486,-0.081413,-0.038720,-0.053610,0.059685,-0.076395,-0.037129,-0.042499
...,...,...,...,...,...,...,...,...,...,...
106,-0.096328,-0.044642,-0.076264,-0.043542,-0.045599,-0.034821,0.008142,-0.039493,-0.059471,-0.083920
270,0.005383,0.050680,0.030440,0.083844,-0.037344,-0.047347,0.015505,-0.039493,0.008641,0.015491
348,0.030811,-0.044642,-0.020218,-0.005670,-0.004321,-0.029497,0.078093,-0.039493,-0.010903,-0.001078
435,-0.012780,-0.044642,-0.023451,-0.040099,-0.016704,0.004636,-0.017629,-0.002592,-0.038460,-0.038357
102,-0.092695,-0.044642,0.028284,-0.015999,0.036958,0.024991,0.056003,-0.039493,-0.005142,-0.001078

In [445]:
X_test

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
287,0.045341,-0.044642,-0.006206,-0.015999,0.125019,0.125198,0.019187,0.034309,0.032432,-0.005220
211,0.092564,-0.044642,0.036907,0.021872,-0.024960,-0.016658,0.000779,-0.039493,-0.022517,-0.021788
72,0.063504,0.050680,-0.004050,-0.012556,0.103003,0.048790,0.056003,-0.002592,0.084492,-0.017646
321,0.096197,-0.044642,0.051996,0.079265,0.054845,0.036577,-0.076536,0.141322,0.098648,0.061054
73,0.012648,0.050680,-0.020218,-0.002228,0.038334,0.053174,-0.006584,0.034309,-0.005142,-0.009362
...,...,...,...,...,...,...,...,...,...,...
255,0.001751,-0.044642,-0.065486,-0.005670,-0.007073,-0.019476,0.041277,-0.039493,-0.003301,0.007207
90,0.012648,-0.044642,-0.025607,-0.040099,-0.030464,-0.045155,0.078093,-0.076395,-0.072133,0.011349
57,-0.027310,-0.044642,-0.063330,-0.050427,-0.089630,-0.104340,0.052322,-0.076395,-0.056153,-0.067351
391,-0.023677,-0.044642,-0.069797,-0.064199,-0.059359,-0.050478,0.019187,-0.039493,-0.089133,-0.050783
24,-0.063635,-0.044642,0.035829,-0.022885,-0.030464,-0.018850,-0.006584,-0.002592,-0.025953,-0.054925

Initialize the model in the variable `diabetes_model`

In [446]:
from sklearn.linear_model import LinearRegression
diabetes_model =LinearRegression()

In the cell below, fit the model and print the intercept and coefficients of the model.

In [447]:
diabetes_model.fit (X_train, y_train)

LinearRegression()

In [448]:
# Print the intercept
print("Intercept:", diabetes_model.intercept_)

Intercept: 151.34560453985995

In [449]:
# Print the coefficients
print("Coefficients:", auto_model.coef_)

Coefficients: [-0.116173    0.00101347 -0.00227634 -0.00656101  0.06173551  0.76063644]

In [450]:
y_pred =diabetes_model.predict(X_test)
y_pred

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59678023,
       130.70432536, 202.18534537, 171.13039501, 164.91423047,
       124.72472569, 144.81030894, 181.99635452, 199.41369642,
       234.21436188, 145.95665512,  79.86703276, 157.36941275,
       192.74412541, 208.89814032, 158.58722555, 206.02195855,
       107.47971675, 140.93598906,  54.82129332,  55.92573195,
       115.01180018,  78.95584188,  81.56087285,  54.37997256,
       166.2543518 ])

In [451]:
from sklearn.metrics import mean_squared_error, r2_score

print("MSE:", mean_squared_error(y_test, y_pred))
print("R²:", r2_score(y_test, y_pred))

MSE: 2900.19362849348
R²: 0.4526027629719197

# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Result should look like this:

![image.png](attachment:image.png)

# Challenge 3 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [452]:
import pandas as pd
auto = pd.read_csv(r"C:\Users\Shrabani P\IronHack\Week2_Day1\Lab_Week2_Day1\lab-intro-to-sklearn-en\Data\auto-mpg.csv")

Look at the first 5 rows using the `head()` function:

In [453]:
auto.head()

,mpg,cylinders,displacement,horse_power,weight,acceleration,model_year,car_name
0,18.0,8,307.0,130.0,3504,12.0,70,"\t""chevrolet chevelle malibu"""
1,15.0,8,350.0,165.0,3693,11.5,70,"\t""buick skylark 320"""
2,18.0,8,318.0,150.0,3436,11.0,70,"\t""plymouth satellite"""
3,16.0,8,304.0,150.0,3433,12.0,70,"\t""amc rebel sst"""
4,17.0,8,302.0,140.0,3449,10.5,70,"\t""ford torino"""

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [454]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horse_power   392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   car_name      398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

What is the newest model year and the oldest model year?

In [455]:
newest_model_year = auto['model_year'].max()
newest_model_year

82

In [456]:
oldest_model_year = auto['model_year'].min()
oldest_model_year

70

Check the dataset for missing values and remove all rows containing at least one missing value.

In [457]:
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     6
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

In [458]:
auto.dropna(axis=0, how="any", inplace=True)

In [459]:
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     0
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [460]:
auto['cylinders'].value_counts()

cylinders
4    199
8    103
6     83
3      4
5      3
Name: count, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [461]:
auto.drop(columns='car_name', inplace =True)

In [462]:
auto.head()

,mpg,cylinders,displacement,horse_power,weight,acceleration,model_year
0,18.0,8,307.0,130.0,3504,12.0,70
1,15.0,8,350.0,165.0,3693,11.5,70
2,18.0,8,318.0,150.0,3436,11.0,70
3,16.0,8,304.0,150.0,3433,12.0,70
4,17.0,8,302.0,140.0,3449,10.5,70

In [467]:
auto.shape

(392, 7)

Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [468]:
X = auto.drop(columns=['mpg'])
y = auto['mpg']

In [469]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
X_train

     cylinders  displacement  horse_power  weight  acceleration  model_year
260          6         225.0        110.0    3620          18.7          78
184          4         140.0         92.0    2572          14.9          76
174          6         171.0         97.0    2984          14.5          75
64           8         318.0        150.0    4135          13.5          72
344          4          86.0         64.0    1875          16.4          81
..         ...           ...          ...     ...           ...         ...
72           8         304.0        150.0    3892          12.5          72
107          6         232.0        100.0    2789          15.0          73
272          4         151.0         85.0    2855          17.6          78
352          4          98.0         65.0    2380          20.7          81
103          8         400.0        150.0    4997          14.0          73

[313 rows x 6 columns]

In [470]:
X_test

     cylinders  displacement  horse_power  weight  acceleration  model_year
79           4          96.0         69.0    2189          18.0          72
276          4         121.0        115.0    2795          15.7          78
248          4          91.0         60.0    1800          16.4          78
56           4          91.0         70.0    1955          20.5          71
393          4         140.0         86.0    2790          15.6          82
..         ...           ...          ...     ...           ...         ...
366          6         225.0         85.0    3465          16.6          81
83           4          98.0         80.0    2164          15.0          72
115          8         350.0        145.0    4082          13.0          73
3            8         304.0        150.0    3433          12.0          70
18           4          97.0         88.0    2130          14.5          70

[79 rows x 6 columns]

Next, fit the model in the cell below.

In [471]:
from sklearn.linear_model import LinearRegression

auto_model = LinearRegression()

In [472]:
auto_model.fit(X_train, y_train)

LinearRegression()

# Challenge 4 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [473]:
y_pred = auto_model.predict(X_test)

In [474]:
y_pred

array([25.93279618, 26.29927859, 32.96548909, 26.8544302 , 29.45372581,
       29.08699476,  7.63874768, 29.23704446, 20.87736024, 28.91582943,
       12.48503673, 23.69898277, 16.41889199, 28.19668802, 22.03967916,
       30.88152399, 21.18311073, 31.64662323, 27.91649795, 29.78148169,
       19.84374006, 34.37342564, 33.99070737, 15.02368137, 28.76984129,
       25.99468114, 20.82555389, 16.63300722, 28.50008896, 23.82955469,
       12.81866721, 23.60612254, 21.36279705, 29.88377781, 11.05575113,
       34.7003572 , 10.84515757, 26.26088449, 11.58087074,  7.71809963,
       12.77118771, 27.81143288, 34.74146456, 26.49024951, 11.3582456 ,
        9.10855962, 17.66893597, 31.4355561 , 25.43286643, 30.38576336,
       11.60450412, 25.152572  , 24.52253515, 33.49442837, 28.90462724,
       17.82504408, 20.7761521 , 23.16942494, 23.10923128, 24.6273826 ,
        7.683821  , 22.9296696 , 27.33070582, 23.09519024, 28.13950034,
       28.69699507, 26.85355066, 29.61277981, 22.23472064,  9.37750077,
       23.83479875, 13.39811055, 25.16730444, 26.8841077 , 24.18222144,
       25.88860198, 13.58449896, 15.4409455 , 24.54031132])

#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_train` data and the predicted `y_test_pred`.

In [475]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

R² Score: 0.794234907542859

# Challenge 5 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [476]:
from sklearn.model_selection import train_test_split

X_train09, X_test09, y_train09, y_test09 = train_test_split(X, y, test_size=0.10, random_state=42)

X_test09

     cylinders  displacement  horse_power  weight  acceleration  model_year
79           4          96.0         69.0    2189          18.0          72
276          4         121.0        115.0    2795          15.7          78
248          4          91.0         60.0    1800          16.4          78
56           4          91.0         70.0    1955          20.5          71
393          4         140.0         86.0    2790          15.6          82
205          4          97.0         75.0    2155          16.4          76
43           8         400.0        170.0    4746          12.0          71
235          4          97.0         75.0    2265          18.2          77
152          6         225.0         95.0    3264          16.0          75
117          4          68.0         49.0    1867          19.5          73
9            8         390.0        190.0    3850           8.5          70
210          6         156.0        108.0    2930          15.5          76
289          8         350.0        155.0    4360          14.9          79
167          4          97.0         75.0    2171          16.0          75
277          6         163.0        133.0    3410          15.8          78
367          4         112.0         88.0    2605          19.6          82
125          6         198.0         95.0    3102          16.5          74
356          4         108.0         75.0    2350          16.8          81
296          4         121.0         80.0    2670          15.0          79
335          4         122.0         88.0    2500          15.1          80
15           6         198.0         95.0    2833          15.5          70
394          4          97.0         52.0    2130          24.6          82
349          4          91.0         68.0    1985          16.0          81
0            8         307.0        130.0    3504          12.0          70
142          4          79.0         67.0    1963          15.5          74
114          4          98.0         90.0    2265          15.5          73
78           4         120.0         87.0    2979          19.5          72
34           6         225.0        105.0    3439          15.5          71
102          4          97.0         46.0    1950          21.0          73
77           4         121.0         76.0    2511          18.0          72
157          8         350.0        145.0    4440          14.0          75
257          6         232.0         90.0    3210          17.2          78
291          8         267.0        125.0    3605          15.0          79
358          4         120.0         74.0    2635          18.3          81
91           8         400.0        150.0    4464          12.0          73
385          4          91.0         67.0    1995          16.2          82
139          8         302.0        140.0    4638          16.0          74
58           4          97.5         80.0    2126          17.0          72
74           8         302.0        140.0    4294          16.0          72
25           8         360.0        215.0    4615          14.0          70

In [477]:
X_test09

     cylinders  displacement  horse_power  weight  acceleration  model_year
79           4          96.0         69.0    2189          18.0          72
276          4         121.0        115.0    2795          15.7          78
248          4          91.0         60.0    1800          16.4          78
56           4          91.0         70.0    1955          20.5          71
393          4         140.0         86.0    2790          15.6          82
205          4          97.0         75.0    2155          16.4          76
43           8         400.0        170.0    4746          12.0          71
235          4          97.0         75.0    2265          18.2          77
152          6         225.0         95.0    3264          16.0          75
117          4          68.0         49.0    1867          19.5          73
9            8         390.0        190.0    3850           8.5          70
210          6         156.0        108.0    2930          15.5          76
289          8         350.0        155.0    4360          14.9          79
167          4          97.0         75.0    2171          16.0          75
277          6         163.0        133.0    3410          15.8          78
367          4         112.0         88.0    2605          19.6          82
125          6         198.0         95.0    3102          16.5          74
356          4         108.0         75.0    2350          16.8          81
296          4         121.0         80.0    2670          15.0          79
335          4         122.0         88.0    2500          15.1          80
15           6         198.0         95.0    2833          15.5          70
394          4          97.0         52.0    2130          24.6          82
349          4          91.0         68.0    1985          16.0          81
0            8         307.0        130.0    3504          12.0          70
142          4          79.0         67.0    1963          15.5          74
114          4          98.0         90.0    2265          15.5          73
78           4         120.0         87.0    2979          19.5          72
34           6         225.0        105.0    3439          15.5          71
102          4          97.0         46.0    1950          21.0          73
77           4         121.0         76.0    2511          18.0          72
157          8         350.0        145.0    4440          14.0          75
257          6         232.0         90.0    3210          17.2          78
291          8         267.0        125.0    3605          15.0          79
358          4         120.0         74.0    2635          18.3          81
91           8         400.0        150.0    4464          12.0          73
385          4          91.0         67.0    1995          16.2          82
139          8         302.0        140.0    4638          16.0          74
58           4          97.5         80.0    2126          17.0          72
74           8         302.0        140.0    4294          16.0          72
25           8         360.0        215.0    4615          14.0          70

In [478]:
print(X_train09.shape)
print(X_test09.shape)
print(y_train09.shape)
print(y_test09.shape)

(352, 6)
(40, 6)
(352,)
(40,)

Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [479]:
auto_model09 = LinearRegression()
auto_model09.fit(X_train09, y_train09)

LinearRegression()

Compute the predicted values and r squared score for our new model and new sample data.

In [480]:
y_pred09 = auto_model09.predict(X_test09)
y_pred09

array([25.79500879, 26.30607444, 32.72173147, 26.76455357, 29.32069319,
       28.92374612,  7.92293591, 29.07543422, 20.77292415, 28.65066633,
       12.87802843, 23.51587538, 16.49986135, 28.03827358, 21.94037251,
       30.75434656, 21.04766999, 31.44623949, 27.74666775, 29.6547018 ,
       19.75740051, 34.12943268, 33.73702057, 15.0134863 , 28.55382092,
       25.918776  , 20.786725  , 16.59998627, 28.29350268, 23.75655308,
       12.87765797, 23.47874091, 21.1755328 , 29.7008905 , 11.24332729,
       34.4330599 , 10.79531146, 26.17242906, 11.57563638,  8.1727483 ])

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [481]:
from sklearn.metrics import r2_score

r2_score_09 = r2_score(y_test09, y_pred09)
r2_score_09

0.8468911998183241

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [482]:
from sklearn.feature_selection import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [483]:

rfe_model = RFE(estimator=auto_model, n_features_to_select=3)

Fit the model and print the ranking

In [484]:
rfe_model.fit(X, y)

RFE(estimator=LinearRegression(), n_features_to_select=3)

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [485]:
from sklearn.model_selection import train_test_split

# Get the names of the three selected features
selected_features = X.columns[rfe_model.support_]

# Create a reduced feature dataset
X_reduced = X[selected_features]

In [486]:
X_train_reduced, X_test_reduced, y_train_reduced, y_test_reduced = train_test_split(X_reduced, y, test_size=0.2, random_state=42)

In [487]:
X_train_reduced

     cylinders  acceleration  model_year
260          6          18.7          78
184          4          14.9          76
174          6          14.5          75
64           8          13.5          72
344          4          16.4          81
..         ...           ...         ...
72           8          12.5          72
107          6          15.0          73
272          4          17.6          78
352          4          20.7          81
103          8          14.0          73

[313 rows x 3 columns]

In [488]:
X_test_reduced

     cylinders  acceleration  model_year
79           4          18.0          72
276          4          15.7          78
248          4          16.4          78
56           4          20.5          71
393          4          15.6          82
..         ...           ...         ...
366          6          16.6          81
83           4          15.0          72
115          8          13.0          73
3            8          12.0          70
18           4          14.5          70

[79 rows x 3 columns]

Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [489]:
auto_model_reduced = LinearRegression()

auto_model_reduced.fit(X_train_reduced, y_train_reduced)

LinearRegression()

In [490]:
y_pred_reduced =auto_model_reduced.predict(X_test_reduced)
y_pred_reduced

array([24.81049562, 29.53937789, 29.50613216, 23.9218198 , 32.62389148,
       27.96625006, 12.00132787, 28.65070208, 21.05321151, 25.50919581,
       11.39761549, 21.84689951, 18.02312394, 27.21530658, 23.37253344,
       32.43391586, 20.25952351, 31.79695775, 30.34256468, 31.10775634,
       17.22725322, 32.19644633, 31.83495287, 11.23138682, 26.46911248,
       25.69917143, 24.73925476, 17.99719427, 25.43795495, 24.81049562,
       14.98610426, 23.30604197, 18.01837455, 31.72571689, 13.54120997,
       32.59539514, 14.1211754 , 24.85798952, 12.5812933 , 11.13639901,
       12.67628111, 26.46911248, 32.63813965, 26.51660638, 15.00985121,
       13.58870388, 18.02094122, 30.35681285, 25.50919581, 28.07073665,
       11.93008701, 24.92923038, 24.15928933, 32.67613478, 26.50454093,
       20.18828265, 15.00985121, 21.05321151, 23.29436047, 24.23053019,
       13.58870388, 21.74716231, 24.28020681, 27.16781267, 29.58212241,
       27.94250311, 29.55362607, 27.31029439, 17.22468655, 11.32637463,
       23.99306066, 13.49371606, 22.66433447, 28.87520677, 25.64436146,
       24.95297733, 13.49371606, 11.23138682, 23.43684219])

In [491]:
from sklearn.metrics import r2_score


r2_score_reduced = r2_score(y_test_reduced, y_pred_reduced)
r2_score_reduced

0.7149033079956759